### ISSUE TITLE
Restoring a backup results in `"backups.resources.cattle.io" is invalid: spec.preserveUnknownFields: Invalid value: true`

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/backup-restore-operator#186] opened 2022-01-20 19:45 UTC
Full error

```
ERRO[2022/01/20 19:12:15] Error restoring CRDs restoreCRDs: restoreResource: err updating resource CustomResourceDefinition.apiextensions.k8s.io "backups.resources.cattle.io" is invalid: spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead 
ERRO[2022/01/20 19:12:15] error syncing 'restore-from-backup': handler restore: error restoring CRDs, check logs for exact error, requeuing 
```

I believe this relates to https://github.com/kubernetes/kubernetes/issues/94295 since I know 2.1.0 recently updated to v1. Seems that field needs to be specified in the CRDs as false for v1.

## Steps to replicate
1. Install rancher backup helm chart v2.0.1
2. Take a backup
3. Upgrade helm chart to v2.1.0
4. Restore from previous backup

This occurs on any CRD that has any field changes/version changes in the lifetime of the cluster.

## Environment 
Kubernetes version: v1.21.4+rke2r2
Rancher Version: v2.6.3

**Comment by thedadams** [comment] 2022-03-01 03:12
Thanks for reporting this issue.

The difference here seems to be that the CRDs are backed up as `v1beta1` and restored as `v1`, which is causing the break. You would likely not see this issue if you backed up and restored with this same version of the backup-restore-operator (whether that is v2.0.1 or v2.1.0).

It seems that the following work-around would be available:
1. Backup with v2.0.1
2. Restore with v2.0.1
3. Upgrade to v2.1.0
4. Backup with v2.1.0
5. Restore (later) with v2.1.0

At this point, it would seem that this should be documented because of this change with CRDs from `v1beta1` to `v1`.

**Comment by ajacques** [comment] 2022-03-03 05:13
> You would likely not see this issue if you backed up and restored with this same version of the backup-restore-operator

I'm also encountering this issue. However my backup and restore operator are both at v2.1.0. I'm trying to move from one cluster (local, k8s v1.21.3+k3s1) to another (prod, k8s v1.21.9) as per the [official migration guide](https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/).

On my source cluster (local), it shows `v1` not `v1beta`.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: listenconfigs.management.cattle.io
```

**Comment by thedadams** [comment] 2022-03-03 05:22
@ajacques Thank you for your example. This is something that should be investigated further.

**Comment by thomashoell** [comment] 2022-03-03 08:44
> > You would likely not see this issue if you backed up and restored with this same version of the backup-restore-operator
> 
> I'm also encountering this issue. However my backup and restore operator are both at v2.1.0. I'm trying to move from one cluster (local, k8s v1.21.3+k3s1) to another (prod, k8s v1.21.9) as per the [official migration guide](https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/).
> 
> On my source cluster (local), it shows `v1` not `v1beta`.
> 
> ```
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
>   generation: 1
>   name: listenconfigs.management.cattle.io
> ...
> ```

This probably was the problem with my cluster as well. I updated _rancher-backup-crd_ from 2.0.1 to 2.1.0 in my source cluster and somehow the CRDs didn't update.

**Comment by superseb** [comment] 2022-04-06 07:01
This seems to be related to https://github.com/rancher/backup-restore-operator/pull/171, especially the parts where apIVersion was changed from v1beta1 to v1 (like https://github.com/rancher/backup-restore-operator/pull/171/files#diff-eeb619ebf95aface21774d20a8d0b4b7cae625cfb01889ff4a6218c6a64effecL30)

What seems to happen is that resources are backed up as v1 but the resource is not valid according to v1, as it contains fields that are no longer accepted and it missing fields (like `openAPIV3Schema`).

First workaround for new backups would be to change the `apiVersion` for `resourceNameRegexp: "management.cattle.io$|project.cattle.io$|catalog.cattle.io$|resources.cattle.io$"` in the resourceset back to `v1beta` and create a new backup after changing it. You can do this by using `kubectl edit resourceset`.

For the real solution, I'm figuring out if we can convert "v1" resources to actually be valid for v1 or that we need to change something else to make sure we can successfully backup and restore between different versions.

**Comment by ADustyOldMuffin** [comment] 2022-04-06 13:23
I think it makes more sense to try and fix the issue in the operator. The most common issue is going to be the missing preserve delete fields, field. This is the issue with all of the Rancher charts. This is something that if fixed by the operator would allow users to continue the restore without needing the CRD creators to fix the issue as it might be quite a few, and the field itself shouldn't cause many issues.

It's also of note in this issue, that this causes an infinite retry loop which probably shouldn't happen and it should stop after 3-5 tries.

**Comment by superseb** [comment] 2022-04-06 15:46
The issue is going to be fixed in the operator, see the last line of https://github.com/rancher/backup-restore-operator/issues/186#issuecomment-1089895190. The workaround is offered for people to continue before a new release of the operator is here.

**Comment by laurie-kepford** [comment] 2022-04-07 15:42
> management.cattle.io

Just to clarify about the work around. In my SOURCE cluster, I have only one resource set. Its called rancher-resource-set.  The current relevant settings are like this:

```
management.cattle.io$|project.cattle.io$|catalog.cattle.io$|resources.cattle.io$
  API Version:           management.cattle.io/v3
  Exclude Kinds:
    tokens
  Kinds Regexp:  .
  API Version:   management.cattle.io/v3
```

You are suggesting that I should replace the 'v3' with 'v1beta'.  Then create a backup and restore it to my new cluster.  No changes needed on the new cluster?  I checked and these settings match what is in my new cluster.

**Comment by superseb** [comment] 2022-04-08 08:59
No, see the linked PR changes in my earlier comment where it shows the changed line from `v1beta` to `v1`. I only have run one test with this workaround as I continued on with the fix in the operator (which is now up and linked to this issue).

Did anyone try to use v2.0.1 to backup and restore? As that doesn't contain the v1/v1.22 change, I expect it to work. I haven't had the time to test it yet, I've been running tests for the operator fix past days.

**Comment by laurie-kepford** [comment] 2022-04-18 13:58
Any idea when your PR will be reviewed?

**Comment by superseb** [comment] 2022-04-25 14:08
### Root cause

Rancher creates CRDs with violations (see below) which are permitted and automatically migrated on upgrade, but when you try to restore such a resource, it won't allow it to be created with the exact resource specifications.

```
  - lastTransitionTime: "2022-04-25T13:55:34Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```
 
### What was fixed, or what changes have occurred

The logic in the restore process will convert the invalid setting (`true`) for `spec.preserveUnknownFields`, to `false` and set the new configuration setting (`x-preserve-unknown-fields`)
 
### Areas or cases that should be tested

Backup and restore of all supported k8s versions for working behavior
 
### What areas could experience regressions?

Restore of any created archive (v2.6.0/v2.6.1/v2.6.2) and newest versions (v2.6.3/v2.6.4)
 
### Are the repro steps accurate/minimal?

1. Create a k8s cluster on 1.21 (I used RKE1 with `v1.21.10-rancher1-1`)
2. Install Rancher v2.6.2 (this won't show using v2.6.3 or v2.6.4)
3. Install backup-restore-operator v2.1.1 using Helm or the UI
4. Create a backup
5. Clean the cluster using the cleanup script or create a new cluster
6. Install backup-restore-operator v2.1.1 using Helm
7. Restore the backup created in step 4
8. Observe logs showing `Error restoring CRDs restoreCRDs`, `is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]`

**Comment by anupama2501** [comment] 2022-05-10 20:06
Reproduced the issue:
Rancher version: `v2.6.2`, k8s: `v1.21.12`, backup-charts: `v2.1.1`

1. Installed rancher on an rke1 cluster version v1.21.12 on 2.6.2 with a downstream cluster created
2. Installed rancher backup chart v2.1.1 and took a backup b1
3. Upgraded rancher to v2.6.5-rc8
4. Tried to restore on the same cluster, therefore ran cleanup script on the local cluster
5. Post cleanup script, when the backup is restored hit the below error

```
ERRO[2022/05/10 19:30:36] Error restoring CRDs restoreCRDs: CustomResourceDefinition.apiextensions.k8s.io "roletemplates.management.cattle.io" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]
ERRO[2022/05/10 19:30:36] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing
```

**Comment by anupama2501** [comment] 2022-05-10 21:55
Verified Rancher version: v2.6.2, k8s: v1.21.12, backup-charts: v2.0.1, post rancher upgrade: v2.6.5-rc8, k8s v1.21.12, backup-charts: `2.1.2-rc4` 

1. Installed rancher on an rke1 cluster version v1.21.12 on 2.6.2 with a downstream cluster created
2. Installed rancher backup chart v2.1.1 and took a backup b1
3. Upgraded rancher to v2.6.5-rc8
4. Create a few resources in the downstream clusters.
5. Run the cleanup script on the local cluster
6. Once the cleanup finishes, install the chart `v2.1.2-rc4`.
7. Restore goes through successfully.
8. Install rancher version v2.6.5-rc8, verify rancher comes up active without any error.

**Closed by anupama2501** 2022-05-10 21:55 UTC
Labels: [zube]: QA Working, internal, release-note, team/area3, area/backup-recover
