### ISSUE TITLE
Restoring rancher mgr from minio/s3 backup results in "creatorID annotation cannot be changed" for vsphere downstream

### ISSUE THREAD

**Issue by jbartlet** [rancher/backup-restore-operator#378] opened 2023-07-25 17:41 UTC
**Rancher Server Setup**
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart): helm chart
- Kubernetes Version and Engine: v1.24.15+rke2r1 

**Describe the bug**
When restoring the Rancher mgr to a new cluster with same Rancher/k8s version, the restore runs successfully for a bit then fails while trying to restore resources for a downstream cluster (vmwarevsphereconfigs, clusters) in fleet-default namespace. The error is 'Error restoring namespaced resources [error restoring qamachine of type rke-machine-config.cattle.io/v1, Resource=vmwarevsphereconfigs: restoreResource: err updating resource admission webhook "rancher.cattle.io.rke-machine-config.cattle.io" denied the request: creatorID annotation cannot be changed'. Also see 'error restoring qacluster of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed'. The restore then re-queues and fires again. If restore is manually terminated after this error, downstream becomes healthy. Not sure if restore is fully complete or not.

**To Reproduce**
1. Deploy HA Rancher cluster, install Rancher Backup
2. Deploy a downstream vsphere cluster
3. Create a one time backup to Minio (S3) target
4. Destroy HA Rancher cluster, rebuild it with same Rancher version and k8s version, install Rancher Backup
5. Create a restore resource, start restore. Restore starts successfully.
6. Receive an error that content cannot be created in namespace cluster-fleet-default-qacluster-f3af050068a3 because the namespace is terminating. Manually delete the namespace, otherwise this repeats infinitely (delete succeeds). Restore re-queues automatically.
7. The next automatic run of the restore gives the errors in description. The (existing) downstream cluster state in UI shows "In Progress" and "Cluster generation is 1, but latest observed generation is 2".
8. If I delete the restore resource at this point, the downstream cluster runs through a quick 'provisioning' run, but doesn't redeploy any machines, then goes active. Everything seems ok.

**Expected behavior**
The restore should complete and the existing downstream vsphere cluster should appear Active. Terminating a restore prior to completion seems sketchy to me.

**Screenshots**

**Additional context**
We deploy our downstream vsphere clusters via Helm chart installed to fleet-default (e.g. https://github.com/rancher/cluster-template-examples)

**Comment by jbartlet** [comment] 2023-07-26 13:35
I should clarify, what I am trying to understand is if cancelling the backup at that point leaves me with a fully restored system or if the only way to be sure is 100% error free completion.

**Comment by jbartlet** [comment] 2023-07-26 18:20
Scratch that, it isn't ok. Lots of errors indicating the 'local' cluster has more than one System project after restore was run.

**Comment by eliyamlevy** [comment] 2023-09-13 21:12
Was Rancher installed at any point in those steps?

**Comment by eliyamlevy** [comment] 2023-09-13 21:13
Also the issues seen in step 6 will be fixed in the next release (`v102.0.2+up3.1.2`)

**Comment by MKlimuszka** [comment] 2023-09-20 17:46
@eliyamlevy, so is there anything else that needs to be done on this ticket, or should this be moved to QA for testing? If so, which Rancher milestone?

**Comment by jbartlet** [comment] 2023-09-20 20:15
@eliyamlevy OK, that I had obviously not figured out, as I did install Rancher then run the restore. So, if we have a disaster happen and the original HA Rancher cluster is lost, the Rancher backups can't be used for recovery? The doc mentions 'A restore refers to restoring a backup to the same cluster it was taken from.' but in the same section (next bullet) mentions '...This allows you to install Rancher Backups again and restore to a completely fresh cluster.' I am clearly having issues connecting the dots here.

**Comment by eliyamlevy** [comment] 2023-10-10 18:55
@jbartlet Sorry for the late reply, the issue is simply that Rancher was installed before you ran the restore. If you are restoring to a cluster with Rancher running make sure to either run the restore from the UI and have prune enabled, or if installing to a fresh cluster to only install the rancher helm chart _**after**_ the restore is complete.

**Comment by MKlimuszka** [comment] 2023-11-29 18:13
Closing as Eli's last comment explains the issue.

**Closed** 2023-11-29 18:13 UTC
Labels: area/vsphere
