### ISSUE TITLE
New rancher installation backup fails with: creatorID annotation cannot be changed

### ISSUE THREAD

**Issue by kgtw** [rancher/backup-restore-operator#172] opened 2021-11-15 15:38 UTC
On a fresh rancher installation on RKE2, that only has the rancher-server installed, the backup is failing with the following error message. We haven't been able to reproduce this 100%, but this has happened more than once now when trying to validate the backup reliability of rancher managed backups.

```
ERRO[2021/11/15 15:20:04] Error restoring namespaced resources [error restoring c-ksrz7 of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancherauth.cattle.io" denied the request: creatorID annotation cannot be changed]
ERRO[2021/11/15 15:20:04] error syncing 'restore-xslk9': handler restore: error restoring namespaced resources, check logs for exact error, requeuing
```

Error seems to be thrown here: https://github.com/rancher/backup-restore-operator/blob/v2.0.1/pkg/controllers/restore/controller.go#L253

Which I believe is actually returned from the webhook service: https://github.com/rancher/webhook/blob/v0.2.1/pkg/resources/validation/cluster/provisioningcluster.go#L140-L145

Rancher Server: v.2.6.2
RKE2: v1.21.5+rke2r2
Rancher Backup Operator: v2.0.1

Steps to reproduce.

1. Install rancher
2. Configure backups, for this we used s3 as the storage location.
3. Create a "Custom" cluster via the UI, but don't register any nodes with it. Purely testing the ability to restore that "cluster" object/reference.
4. Take a manual backup.
5. Delete the "Custom" cluster from the UI.
6. Restore from manual backup.
7. Observe logs in `rancher-backup` pod failing because of error mentioned above. 

**Update:**

Investigated further, not sure if this is intended operation but the `field.cattle.io/creatorId` value from the backup is being overridden with `system:serviceaccount:cattle-resources-system:rancher-backup`.

Backup value in tar.gz: `"field.cattle.io/creatorId": "system:serviceaccount:cattle-system:rancher"`
After backup is applied (with `ignoreErrors: true`): `"field.cattle.io/creatorId": "system:serviceaccount:cattle-resources-system:rancher-backup"`

**Comment by riuvshyn** [comment] 2021-11-17 10:05
is deleting cluster and then trying to restore it from backup even a valid usecase?

**Comment by MKlimuszka** [comment] 2022-12-07 21:17
@nickwsuse has been able to reproduce this, but it took multiple attempts. It appears similar to these tickets:
https://github.com/rancher/backup-restore-operator/issues/279
https://github.com/rancher/backup-restore-operator/issues/280

**Comment by MKlimuszka** [comment] 2022-12-07 21:19
I am marking this as priority/1 because it is the same reproduction steps as a newer escalation.

**Comment by philipsparrow** [comment] 2023-02-09 22:13
I am seeing the same error when restoring a backup to a new cluster (GKE). Rancher 2.6.5

**Comment by eliyamlevy** [comment] 2023-04-04 16:49
It seems like this is what is happening:

1. Webhook is running in the target cluster.
2. We try to restore a backup with a different creator id than the backup SA
3. Webhook changes the creator id to be the backup SA instead of the user who actually created
4. Wrangler sees that there's a difference in the desired
5. Wrangler attempts to update the creator id, and fails

This is probably happening because Rancher is already running in the cluster we are restoring to. According to [rancher migration docs](https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster) "If you are migrating Rancher to a new Kubernetes cluster, you don't need to install Rancher on the new cluster first. **If Rancher is restored to a new cluster with Rancher already installed, it can cause problems**."

The best solution would be to make sure the restore is happening on a fresh cluster. Please check that Rancher is not already installed on the cluster you're migrating to. We are looking into this to see if there is a deeper issue, so please let us know if this fixes the errors you're seeing.

**Comment by eliyamlevy** [comment] 2023-04-04 16:52
> is deleting cluster and then trying to restore it from backup even a valid usecase?

Depends on if deleting the cluster resource signals the downstream cluster to destroy itself.

**Closed** 2023-05-24 22:49 UTC
Labels: [zube]: Need Info, internal, team/area3, area/backup-recover, priority/1, team/area1

**Comment by eliyamlevy** [comment] 2023-06-09 20:06
Please see my comment here: #279 (comment)
