### ISSUE TITLE
Backup to s3 behind http_proxy

### ISSUE THREAD

**Issue by Earsil** [rancher/backup-restore-operator#106] opened 2021-05-19 14:14 UTC
Hi,
It seems that is not possible to set proxy settings for backup pods anywhere in the helm chart. Therefore, when I run backups they get timeout.  They get stuck here:
```
INFO[2021/05/19 14:04:40] invoking set s3 service client                s3-accessKey=**** s3-bucketName=***** s3-endpoint=* s3-endpoint-ca= s3-folder=rancher s3-region=***
```
I also ensured that backup pods don't get any proxy settings from main rancher.

```
## kubectl exec  --namespace=cattle-resources-system   -it rancher-backup-7f686dcbd6-6pnnv -- env

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=rancher-backup-7f686dcbd6-6pnnv
CHART_NAMESPACE=cattle-resources-system
DEFAULT_S3_BACKUP_STORAGE_LOCATION=rancher-backup-s3
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
TERM=xterm
HOME=/root
```

So I assume, it is a feature request ;) Please add HTTP_PROXY, HTTPS_PROXY and NO_PROXY settings

**Comment by Earsil** [comment] 2021-05-19 14:31
FYI, workaround is to edit proper deployment
```
kubectl edit deployments.apps rancher-backup --namespace=cattle-resources-system
```
and add proxy settings there.

**Comment by MKlimuszka** [comment] 2022-04-19 16:44
https://github.com/rancher/charts/pull/1859 This can be tested once this PR is merged.

**Comment by superseb** [comment] 2022-04-25 12:32
### Root cause

Not able to configure proxy in the Helm chart
 
### What was fixed, or what changes have occurred
 
Ability to configure proxy using `--set proxy=proxy.yourdomain.com`

### Areas or cases that should be tested

- Does it work behind a proxy after configuring it
- Are the correct environment variables set in the container (`HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY`)
 
### What areas could experience regressions?
 
Any operation

### Are the repro steps accurate/minimal?

Yes

**Comment by Jono-SUSE-Rancher** [comment] 2022-05-10 17:16
@superseb - There isn't any QA available currently to perform the required validation for this ticket, so we are going to let it go without validation for 2.6.5 and validate it for the next milestone.

**Comment by MSpencer87** [comment] 2022-05-17 00:21
_Verified on Rancher 2.6.5_ 
_Rancher Backups Chart Version: 2.1.2_
1. Run RancherQA Proxy job
2. Install Rancher Backups 2.1.1 
	a. Apps -> Charts
	b. Set values in the yaml `proxy: your.proxy.ip` and `noProxy: from the Jenkins job output`
	c. Once installed, confirm pod does not have settings applied 
         - ```kubectl get pods -A``` grab rancher-backup pod's name
         -  ```kubectl exec  --namespace=cattle-resources-system   -it rancher-backup-pod-name -- env```
         -  Output **does not** contain **HTTP_PROXY, HTTPS_PROXY, NO_PROXY**

3. Create secret for s3 credentials for Google Storage(outside AWS)
	a. Main Menu -> Google Storage -> Create Bucket
	b. Settngs -> Interoperability -> Access keys for your user account -> Create a Key
	c. Core -> Secrets -> Opaque, enter keys as `accessKey` and `secretKey` with corresponding values
4. Create a backup
	a. Select secret for s3 Google Storage
	b. Enter bucket name
	c. Enter region\folder(if specified, I used Multi-region without any folder so I left both blank)
	d. Use `storage.googleapis.com` as endpoind
	e. Confirm backup fails to Retrying state, view logs to confirm the operation is stuck
		- ```kubectl logs -n cattle-resources-system -lapp.kubernetes.io/name=rancher-backup -f```
5. Delete/Install or Upgrade to Rancher Backups 2.1.2
	a. Set values in the yaml `proxy: your.proxy.ip` and `noProxy: from the Jenkins job output` OR utilize `--set proxy=your.proxy.ip` for the helm installation
	b. Once installed/upgrade, confirm pod **DOES** have settings applied 
		 - ```kubectl get pods -A``` grab rancher-backup pod's name
	         -  ```kubectl exec  --namespace=cattle-resources-system   -it rancher-backup-pod-name -- env```
	         - Output **DOES** contain **HTTP_PROXY, HTTPS_PROXY, NO_PROXY**
6. Create a backup
	a. Select secret for s3 Google Storage
	b. Enter bucket name
	c. Enter region\folder(if specified, I used Multi-region without any folder so I left both blank)
	d. Use `storage.googleapis.com` as endpoind
	e. Confirm backup **is successful to Completed state**, view logs to confirm the operation is complete, view Google Storage to see backup file was created
		- ```kubectl logs -n cattle-resources-system -lapp.kubernetes.io/name=rancher-backup -f```

**Closed by MSpencer87** 2022-05-17 00:21 UTC
Labels: [zube]: QA Working, team/area3, area/backup-recover
