### ISSUE TITLE
Unable to perform a restore when Rancher resides in an AKS cluster with a imported generic cluster 

### ISSUE THREAD

**Issue by David-VTUK** [rancher/backup-restore-operator#365] opened 2023-06-19 14:49 UTC
**Rancher Server Setup**
- Rancher version: 2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart
- Kubernetes Version and Engine:  v1.24.9 / AKS

**Describe the bug**
Cannot use the backup operator to restore if running on AKS and have a generic cluster (AKS) cluster imported.

**To Reproduce**

1. Install Rancher on an AKS cluster
2. Install the backup operator in the Rancher management cluster
4. Create a second AKS cluster
5. Import second AKS cluster bu going into `Cluster Management -> Import -> Generic`
6. Create a new local user (for testing)
7. Create a new Backup 
8. Delete the imported cluster
9. Delete the created user
10. Initiate a restore operation.

**Expected behavior**
Restore process to complete

**Additional context**
Rancher pods will enter a creation -> termination -> creation loop. 

Error logs from the Rancher Backup Pod:

```
ERRO[2023/06/19 14:35:14] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:35:15] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:35:16] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:35:20] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:35:28] Error restoring namespaced resources [error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:36:33] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:36:34] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:36:36] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:36:36] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:36:40] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:36:47] Error restoring namespaced resources [error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:36:47] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
ERRO[2023/06/19 14:37:53] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:37:57] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:37:58] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:37:58] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:38:00] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:38:07] Error restoring namespaced resources [error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:38:07] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
ERRO[2023/06/19 14:39:12] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:39:13] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:39:14] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:39:16] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:39:18] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:39:26] Error restoring namespaced resources [error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:39:26] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
ERRO[2023/06/19 14:40:37] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:40:38] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:40:41] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:40:43] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:40:44] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:40:50] Error restoring namespaced resources [error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:40:50] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
ERRO[2023/06/19 14:41:59] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:42:00] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:42:03] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:42:03] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:42:04] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:42:09] Error restoring namespaced resources [error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:42:09] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
ERRO[2023/06/19 14:43:14] Error restoring resource aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed 
ERRO[2023/06/19 14:43:15] Error restoring resource request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:43:17] Error restoring resource request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:43:20] Error restoring resource fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:43:21] Error restoring resource kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated 
ERRO[2023/06/19 14:43:27] Error restoring namespaced resources [error restoring aks-test of type provisioning.cattle.io/v1, Resource=clusters: restoreResource: err updating resource admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: creatorID annotation cannot be changed error restoring request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25 of type /v1, Resource=serviceaccounts: restoreResource: err creating resource serviceaccounts "request-nvt9b-6b46b65c-2e08-4a90-9a09-f81fe3a24f25" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring request-nvt9b of type rbac.authorization.k8s.io/v1, Resource=rolebindings: restoreResource: err creating resource rolebindings.rbac.authorization.k8s.io "request-nvt9b" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring fleet-agent-aks-test of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource bundledeployments.fleet.cattle.io "fleet-agent-aks-test" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated error restoring kube-root-ca.crt of type /v1, Resource=configmaps: restoreResource: err creating resource configmaps "kube-root-ca.crt" is forbidden: unable to create new content in namespace cluster-fleet-default-aks-test-b7b93cc910d0 because it is being terminated] 
ERRO[2023/06/19 14:43:27] error syncing 'restore-s7b7r': handler restore: error restoring namespaced resources, check logs for exact error, requeuing 
```

**Comment by MKlimuszka** [comment] 2023-07-24 20:38
Closing as a duplicate of https://github.com/rancher/rancher/issues/34518

**Closed by MKlimuszka** 2023-07-24 20:38 UTC
Labels: team/area3, area/backup-recover
